### PR TITLE
Feature/privacy manifest

### PR DESCRIPTION
**Pull request by andrija-ostojic**
### This PR adds privacy manifest to the library

- Library version is raised to 1.2.1
- Added 2 input to manifest, one for UserDefaults and one for systemUptime
- Cocoapods integration works
- Generated privacy report finds no issues
- Readme.md is updated

### CODE REVIEW

**Comment by hhrvoic** [comment]
Btw, do we need a privacy manifest for Sentinel - tool used for development/QA builds? AFAIK Sentinel shouldn't be included the App Store builds at all.

**Comment by nikolamajcen** [comment]
@hhrvoic it should not, but with SPM that can be catchy (even there is a solution).

**Comment by goranbrl** [comment]
Keep in mind that even though we don't recommend using the tool in production builds, it's an OSS lib, and it ***can*** be used in them if someone wants to, so we should add the manifest.

**Review by goranbrl — APPROVED** [review]

**Comment by andrija-ostojic** [comment]
What @goranbrl  said, that was my reasoning too

**Review by hhrvoic — APPROVED** [review]

**Pull request merged**
